[project]
name = "hello-alchitry-pt-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "amaranth>=0.5.7",
    "amaranth-boards>=0",
    "amaranth-yosys>=0.50.0.0.post115",
]
